### PR TITLE
Added CSV to Socrata FME template

### PR DESCRIPTION
**Pull request by benunsworth**
New FME template, CSV to Socrata with transformation of date/time and
reprojecting X/Y coordinates to lat/lon

### CODE REVIEW

**Comment by chrismetcalf** [comment]
@alaurenz Looks good to me, your call for the merge.

**Comment by alaurenz** [comment]
@benunsworth thanks for submitting this and it looks great. I thought you had written some accompanying documentation. Do you have that too somewhere?

**Comment by benunsworth** [comment]
@alaurenz sure do, will add to dev.socrata.com

**Comment by alaurenz** [comment]
actually remember you should just add it to the gh-pages branch on the
connectors repo. not the dev.socrata.com repo

**Comment by alaurenz** [comment]
Looks great! This is extremely useful.

**Pull request merged**
